### ISSUE TITLE
Gotta teach Andrew not to be a noob....

### ISSUE THREAD

**Issue by AndrewJohnN** [Vanderscycle/2021-lighthouseLabCodingChallenge#1]
@Vanderscycle glad your tutorials are making me feel less dumb. Goals are as follows:

-    [x] Make Andrew less of a noob

![no idea dog](https://user-images.githubusercontent.com/79022465/108008195-cfc97f80-6fcd-11eb-9f30-f829ae6deac6.png)

**Comment by Vanderscycle** [comment]
here's a simple-ish task to make use of what you learned. Fork the repo and clone it on your local files, create a branch, create a folder, inside the repo, marked 'Andrew' and inside the folder create test.py and inside test.py copy this code ```Python print(hello world!)```. Once done add and commit the files. Push them to your forked repo and then create a pull request.
Here's another good reference for what we are about to do: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by Vanderscycle** [comment]
Also, I am impressed that you used the issue system for that. That was the right thing to do @AndrewJohnN. Please don't forget to first fork the repo and then clone it on your machine.

**Comment by AndrewJohnN** [comment]
so i did fork it but somehow my issues and branches seemed to have appeared in your repo...maybe i accidently started working in it....see closed pull request...

**Comment by Vanderscycle** [comment]
That's normal because the repos are linked together. As the owner, I can reopen the PR.

**Comment by AndrewJohnN** [comment]
Andrew is no longer a noob!
![keanu-reeves-matrix-4](https://user-images.githubusercontent.com/79022465/108012959-a4985d80-6fd8-11eb-8c40-e5f32a69e81a.jpg)
